import { StyleSheet } from "react-native";
import { colors } from "../../../../utilis/colors";
import { fonts } from "../../../../utilis/fonts";
import {
  fontScale,
  horizontalScale,
  verticalScale,
} from "../../../../utilis/appConstant";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gradient_dark_purple,
  },
  header: {
    paddingBottom: verticalScale(2),
    paddingHorizontal: horizontalScale(20),
    alignItems: "center",
  },
  headerTitle: {
    fontSize: fontScale(20),
    marginBottom: verticalScale(23),
    lineHeight: verticalScale(24),
    fontWeight: "600",
    fontFamily: fonts.semiBold,
    color: colors.white,
    textAlign: "center",
  },
  tabContainer: {
    flexDirection: "row",
    marginHorizontal: horizontalScale(20),
    marginBottom: verticalScale(20),
    backgroundColor: "transparent",
    borderRadius: verticalScale(25),
    gap: horizontalScale(12),
  },
  tab: {
    flex: 1,
    paddingVertical: verticalScale(12),
    paddingHorizontal: horizontalScale(20),
    borderRadius: verticalScale(20),
    alignItems: "center",
    justifyContent: "center",
    borderWidth: verticalScale(1),
    borderColor: colors.purpleBorder,
  },
  activeTab: {
    backgroundColor: colors.BtnBackground,
    borderColor: colors.BtnBackground,
  },
  tabText: {
    fontFamily: fonts.medium,
    color: colors.white,
    fontWeight: "500",
    fontSize: fontScale(14),
  },
  activeTabText: {
    fontFamily: fonts.medium,
    color: colors.white,
    fontWeight: "500",
    fontSize: fontScale(14),
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: horizontalScale(20),
  },
  bookingCard: {
    width: horizontalScale(334),
    height: verticalScale(155),
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(16),
    marginBottom: verticalScale(15),
    borderWidth: 1,
    borderColor: colors.requestCardBorder,
    overflow: "hidden",
  },
  rejectedBookingCard: {
    width: horizontalScale(350),
    height: verticalScale(190),
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(16),
    marginBottom: verticalScale(15),
    borderWidth: 1,
    borderColor: colors.red,
    overflow: "hidden",
  },
  lastBookingCard: {
    marginBottom: verticalScale(80),
  },
  lastRejectedBookingCard: {
    marginBottom: verticalScale(80),
  },
  cardContent: {
    flexDirection: "row",
    padding: verticalScale(8),
    flex: 1,
    width: "100%",
    justifyContent: "space-between",
  },
  leftSection: {
    marginRight: horizontalScale(8),
    justifyContent: "flex-start",
    paddingTop: verticalScale(8),
  },
  profileImage: {
    width: horizontalScale(74),
    height: verticalScale(74),
    borderRadius: verticalScale(90),
    borderWidth: verticalScale(2),
    borderColor: colors.BtnBackground,
  },
  rightSection: {
    flex: 1,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  categoryTag: {
    backgroundColor: colors.categoryTagBackground,
    paddingHorizontal: horizontalScale(12),
    paddingVertical: verticalScale(4),
    borderRadius: verticalScale(12),
    alignSelf: "flex-start",
  },
  categoryText: {
    fontSize: fontScale(10),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  actionButtons: {
    flexDirection: "row",
    gap: horizontalScale(8),
  },
  actionButton: {
    width: horizontalScale(32),
    height: verticalScale(32),
    borderRadius: verticalScale(16),
    backgroundColor: colors.addButtonBackground,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  userName: {
    fontSize: fontScale(18),
    fontFamily: fonts.Bold,
    color: colors.white,
    marginBottom: verticalScale(5),
  },
  detailsContainer: {
    flex: 1,
    gap: verticalScale(3),
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(8),
  },
  detailText: {
    fontSize: fontScale(10),
    fontWeight: "400",
    fontFamily: fonts.Regular,
    color: colors.whiteLight,
    flex: 1,
  },
  priceText: {
    fontSize: fontScale(14),
    fontWeight: "800",
    fontFamily: fonts.Bold,
    color: colors.white,
    marginLeft: "auto",
  },
  rejectionRow: {
    width: "100%",
    height: verticalScale(34),
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(8),
    paddingVertical: verticalScale(6),
    paddingHorizontal: horizontalScale(12),
    backgroundColor: colors.rejectionRowBackground,
    borderBottomLeftRadius: verticalScale(16),
    borderBottomRightRadius: verticalScale(16),
    alignSelf: "stretch",
  },
  rejectionText: {
    fontSize: fontScale(11),
    fontFamily: fonts.Medium,
    color: colors.white,
    flex: 1,
  },
  buttonContainer: {
    marginTop: verticalScale(16),
    alignItems: "center",
  },
  acceptButton: {
    width: horizontalScale(159),
    height: verticalScale(40),
    borderRadius: 20,
    backgroundColor: colors.BtnBackground,
    alignItems: "center",
    justifyContent: "center",
  },
  acceptButtonText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Bold,
    color: colors.white,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: verticalScale(50),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: verticalScale(50),
  },
  loadingText: {
    fontSize: fontScale(16),
    fontFamily: fonts.medium,
    color: colors.white,
    marginTop: verticalScale(10),
  },
  emptyText: {
    fontSize: fontScale(16),
    fontFamily: fonts.medium,
    color: colors.whiteLight,
    textAlign: "center",
  },
});
