import { StyleSheet, Platform, Dimensions } from "react-native";
import { colors,  } from "../../../../../utilis/colors";
import { fonts } from "../../../../../utilis/fonts";
import {
  fontScale,
  horizontalScale,
  verticalScale,
} from "../../../../../utilis/appConstant";

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.gradient_dark_purple,
  },
  fullScreenMap: {
    flex: 1,
    width: '100%',
    height: '100%',
    opacity: 0.8
  },
  overlayContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'transparent',
    paddingTop: Platform.OS === 'ios' ? verticalScale(50) : verticalScale(20),
    pointerEvents: 'box-none', // Allow touches to pass through to map
  },
  topSection: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: horizontalScale(16),
    paddingBottom: verticalScale(16),
    zIndex: 10,
    pointerEvents: 'auto', // Allow touches on search bar
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(12),
  },
  locationText: {
    color: colors.white,
    fontFamily: fonts.medium,
    fontSize: fontScale(16),
    marginLeft: horizontalScale(8),
    flex: 1,
  },
  backButton: {
    marginRight: horizontalScale(12),
    padding: horizontalScale(8),
    backgroundColor: colors.cardBackground,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  inputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBackground,
    borderRadius: horizontalScale(20),
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(12),
    marginRight: horizontalScale(12),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  input: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: fontScale(14),
    color: colors.primary_lighter,
    marginLeft: horizontalScale(8),
    padding: 0,
    margin: 0,
    height: verticalScale(20),
  },
  closeIcon: {
    fontSize: fontScale(20),
    color: colors.violate,
    paddingHorizontal: horizontalScale(5),
  },
  filterButtons: {
    flexDirection: 'row',
    gap: horizontalScale(8),
  },
  filterButton: {
    backgroundColor: colors.cardBackground,
    borderRadius: horizontalScale(20),
    width: horizontalScale(40),
    height: horizontalScale(40),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  filterIcon: {
    fontSize: fontScale(16),
    color: colors.violate,
  },
  locationTitleContainer: {
    paddingHorizontal: horizontalScale(16),
    marginBottom: verticalScale(12),
    backgroundColor: 'transparent',
    pointerEvents: 'none', // Don't block map touches
  },
  locationTitle: {
    fontSize: fontScale(20),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(4),
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  locationSubtitle: {
    fontSize: fontScale(16),
    fontFamily: fonts.medium,
    color: colors.white,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  userLocationMarker: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarMarker: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: {
    width: horizontalScale(50),
    height: horizontalScale(50),
    borderRadius: horizontalScale(25),
    borderWidth: 3,
    borderColor: colors.violate,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  highlightedAvatarMarker: {
    shadowColor: colors.violate,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 12,
    elevation: 12,
  },
  distanceText: {
    fontSize: fontScale(10),
    fontFamily: fonts.medium,
    color: colors.white,
    backgroundColor: colors.violate,
    paddingHorizontal: horizontalScale(6),
    paddingVertical: verticalScale(2),
    borderRadius: horizontalScale(8),
    marginTop: verticalScale(4),
    overflow: 'hidden',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  featuredSection: {
    position: 'absolute',
    bottom: verticalScale(20),
    left: 0,
    right: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: horizontalScale(16),
    pointerEvents: 'auto', // Allow touches on featured events
  },
  featuredTitle: {
    fontSize: fontScale(18),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(10),
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  featuredEventsContainer: {
    paddingBottom: verticalScale(20),
  },
  mapLoadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.gradient_dark_purple,
    zIndex: 1,
  },
  mapLoadingText: {
    fontSize: fontScale(16),
    fontFamily: fonts.medium,
    color: colors.white,
  },
  // Event Marker Styles
  eventMarker: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventMarkerImage: {
    width: horizontalScale(50),
    height: horizontalScale(50),
    borderRadius: horizontalScale(25),
    borderWidth: 3,
    borderColor: colors.violate,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  eventMarkerDistance: {
    fontSize: fontScale(10),
    fontFamily: fonts.medium,
    color: colors.white,
    backgroundColor: colors.violate,
    paddingHorizontal: horizontalScale(6),
    paddingVertical: verticalScale(2),
    borderRadius: horizontalScale(10),
    marginTop: verticalScale(4),
    textAlign: 'center',
    minWidth: horizontalScale(40),
  },
});