import { StyleSheet } from "react-native";
import { colors } from "../../../../utilis/colors";
import { fonts } from "../../../../utilis/fonts";
import {
  fontScale,
  horizontalScale,
  verticalScale,
} from "../../../../utilis/appConstant";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundColor,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: verticalScale(20),
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: horizontalScale(20),
    paddingVertical: verticalScale(16),
    borderBottomWidth: 1,
    borderBottomColor: colors.vilate10,
  },
  headerTitle: {
    fontSize: fontScale(18),
    fontFamily: fonts.Bold,
    color: colors.white,
    flex: 1,
    textAlign: "center",
  },
  headerRight: {
    width: horizontalScale(40),
  },
  section: {
    marginTop: verticalScale(24),
    paddingHorizontal: horizontalScale(20),
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: verticalScale(16),
  },
  sectionTitle: {
    fontSize: fontScale(20),
    fontFamily: fonts.Bold,
    fontWeight: "700",
    color: colors.white,
    marginBottom: verticalScale(16),
  },
  sectioncards: {
    fontSize: fontScale(20),
    fontFamily: fonts.Bold,
    fontWeight: "700",
    color: colors.white,
  },
  addCardButton: {
    backgroundColor: colors.violate,
    paddingHorizontal: horizontalScale(12),
    paddingVertical: verticalScale(6),
    borderRadius: horizontalScale(16),
  },
  addCardButtonText: {
    fontSize: fontScale(12),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  addCardSection: {
    marginTop: verticalScale(16),
    paddingTop: verticalScale(16),
    borderTopWidth: 1,
    borderTopColor: colors.vilate20,
  },
  addCardTitle: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
    marginBottom: verticalScale(12),
  },
  cardFieldContainer: {
    marginBottom: verticalScale(16),
  },
  cardField: {
    width: '100%',
    height: verticalScale(50),
  },
  addCardButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: horizontalScale(12),
  },
  cancelButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.vilate20,
    borderRadius: horizontalScale(12),
    paddingVertical: verticalScale(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  addButton: {
    flex: 1,
    backgroundColor: colors.violate,
    borderRadius: horizontalScale(12),
    paddingVertical: verticalScale(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  disabledButton: {
    opacity: 0.6,
  },
  headerButtons: {
    flexDirection: 'row',
    gap: horizontalScale(8),
  },
  refreshButton: {
    backgroundColor: colors.vilate20,
    paddingHorizontal: horizontalScale(8),
    paddingVertical: verticalScale(4),
    borderRadius: horizontalScale(12),
  },
  refreshButtonText: {
    fontSize: fontScale(10),
    fontFamily: fonts.Medium,
    color: colors.white,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: verticalScale(24),
  },
  loadingText: {
    marginTop: verticalScale(8),
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.textcolor,
  },
  errorContainer: {
    alignItems: 'center',
    paddingVertical: verticalScale(24),
    paddingHorizontal: horizontalScale(16),
  },
  errorText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.red,
    textAlign: 'center',
    marginBottom: verticalScale(12),
  },
  retryButton: {
    backgroundColor: colors.violate,
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(8),
    borderRadius: horizontalScale(8),
  },
  retryButtonText: {
    fontSize: fontScale(12),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: verticalScale(24),
    paddingHorizontal: horizontalScale(16),
  },
  emptyStateText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.textcolor,
    marginBottom: verticalScale(16),
  },
  addFirstCardButton: {
    backgroundColor: colors.violate,
    paddingHorizontal: horizontalScale(20),
    paddingVertical: verticalScale(12),
    borderRadius: horizontalScale(8),
  },
  addFirstCardButtonText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  defaultCardIcon: {
    width: horizontalScale(45),
    height: verticalScale(45),
    borderRadius: horizontalScale(8),
    backgroundColor: colors.violate,
    justifyContent: 'center',
    alignItems: 'center',
  },
  defaultCardText: {
    color: colors.white,
    fontSize: fontScale(18),
    fontFamily: fonts.Bold,
    fontWeight: 'bold',
  },
  platformPayContainer: {
    marginTop: verticalScale(16),
    marginHorizontal: horizontalScale(20),
  },
  platformPayButton: {
    width: '100%',
    height: verticalScale(50),
  },
  cardsList: {
    gap: verticalScale(12),
  },
  cardContainer: {
    backgroundColor: colors.unselectedBackground,
    borderRadius: horizontalScale(20),
    borderWidth: 1,
    borderColor: colors.vilate20,
    marginBottom: verticalScale(8),
    overflow: "hidden",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardContent: {
    flexDirection: "row",
    alignItems: "center",
    padding: horizontalScale(16),
    position: "relative",
  },
  cardLeft: {
    marginRight: horizontalScale(16),
  },
  textLogoContainer: {
    width: horizontalScale(50),
    height: verticalScale(30),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderRadius: horizontalScale(6),
    paddingHorizontal: horizontalScale(4),
  },
  logoContainer: {
    width: horizontalScale(50),
    height: verticalScale(30),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderRadius: horizontalScale(6),
    paddingHorizontal: horizontalScale(4),
  },
  textLogo: {
    fontSize: fontScale(14),
    fontFamily: fonts.Bold,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  mastercardLogo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderRadius: horizontalScale(6),
    paddingHorizontal: horizontalScale(4),
    paddingVertical: verticalScale(2),
  },
  mastercardCircle: {
    width: horizontalScale(14),
    height: verticalScale(14),
    borderRadius: horizontalScale(7),
    marginHorizontal: horizontalScale(-1),
  },
  cardRight: {
    flex: 1,
  },
  cardholderName: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
    marginBottom: verticalScale(4),
  },
  cardNumber: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.textcolor,
    letterSpacing: 1,
  },
  deleteButton: {
    position: "absolute",
    top: "50%",
    right: horizontalScale(10),
    width: horizontalScale(20),
    height: verticalScale(20),
    borderRadius: horizontalScale(10),
    backgroundColor: colors.red,
    alignItems: "center",
    justifyContent: "center",
    marginTop: verticalScale(-10),
    shadowColor: colors.red,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  deleteButtonText: {
    fontSize: fontScale(12),
    color: colors.white,
    fontWeight: "400",
    lineHeight: fontScale(12),
  },
  selectedCard: {
    borderColor: colors.violate,
    borderWidth: 2,
  },
  paymentOptionsSection: {
    marginTop: verticalScale(24),
    paddingHorizontal: horizontalScale(20),
    marginBottom: verticalScale(40),
  },
  paymentOptionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.unselectedBackground,
    width: horizontalScale(336),
    height: verticalScale(58),
    borderRadius: horizontalScale(20),
    padding: horizontalScale(16),
    marginBottom: verticalScale(12),
    borderWidth: 1,
    borderColor: colors.vilate20,
    opacity: 1,
  },
  selectedPaymentOption: {
    borderColor: colors.violate,
    borderWidth: 2,
  },
  paymentOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  appleLogo: {
    width: horizontalScale(24),
    height: verticalScale(24),
    alignItems: "center",
    justifyContent: "center",
    marginRight: horizontalScale(12),
  },
  googleLogo: {
    width: horizontalScale(24),
    height: verticalScale(24),
    alignItems: "center",
    justifyContent: "center",
    marginRight: horizontalScale(12),
  },
  paymentOptionText: {
    fontSize: fontScale(16),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  radioButton: {
    width: horizontalScale(20),
    height: verticalScale(20),
    borderRadius: horizontalScale(10),
    borderWidth: 2,
    borderColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  selectedRadioButton: {
    borderColor: colors.violate,
  },
  radioButtonSelected: {
    width: horizontalScale(10),
    height: verticalScale(10),
    borderRadius: horizontalScale(5),
    backgroundColor: colors.violate,
  },
  promoCodeSection: {
    marginTop: verticalScale(20),
    marginBottom: verticalScale(20),
  },
  promoCodeContainer: {
    position: "relative",
    width: horizontalScale(335),
    height: verticalScale(48),
  },
  promoCodeInput: {
    width: "100%",
    height: "100%",
    borderRadius: horizontalScale(90),
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(12),
    paddingRight: horizontalScale(80),
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.white,
    borderWidth: 1,
    borderColor: colors.whiteTransparent,
  },
  applyButton: {
    position: "absolute",
    right: horizontalScale(8),
    top: verticalScale(12),
    width: horizontalScale(66),
    height: verticalScale(24),
    backgroundColor: colors.BtnBackground,
    borderRadius: horizontalScale(90),
    alignItems: "center",
    justifyContent: "center",
  },
  applyButtonText: {
    fontSize: fontScale(12),
    fontWeight: "400",
    fontFamily: fonts.regular,
    color: colors.white,
  },
});
