import { StyleSheet } from "react-native";
import { colors } from "../../../../utilis/colors";
import { fonts } from "../../../../utilis/fonts";
import {
  fontScale,
  horizontalScale,
  verticalScale,
} from "../../../../utilis/appConstant";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradientContainer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: verticalScale(30),
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: horizontalScale(20),
    paddingTop: verticalScale(10),
    paddingBottom: verticalScale(20),
  },
  backButton: {
    width: horizontalScale(40),
    height: verticalScale(40),
    borderRadius: verticalScale(20),
    backgroundColor: colors.addButtonBackground,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: fontScale(18),
    fontFamily: fonts.Bold,
    color: colors.white,
    textAlign: "center",
  },
  headerSpacer: {
    width: horizontalScale(40),
  },
  eventCard: {
    flexDirection: "row",
    backgroundColor: colors.cardBackground,
    marginHorizontal: horizontalScale(20),
    marginBottom: verticalScale(20),
    borderRadius: verticalScale(16),
    padding: verticalScale(12),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    shadowColor: colors.purpleBorder,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  eventImageContainer: {
    position: "relative",
    marginRight: horizontalScale(12),
  },
  eventImage: {
    width: horizontalScale(100),
    height: verticalScale(80),
    borderRadius: verticalScale(12),
  },
  favoriteButton: {
    position: "absolute",
    top: verticalScale(6),
    left: horizontalScale(6),
    width: horizontalScale(24),
    height: verticalScale(24),
    borderRadius: verticalScale(12),
    backgroundColor: colors.violate,
    alignItems: "center",
    justifyContent: "center",
  },
  eventContent: {
    flex: 1,
    justifyContent: "space-between",
  },
  eventHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: verticalScale(8),
  },
  categoryTag: {
    backgroundColor: colors.categoryBackground,
    height: verticalScale(20),
    borderRadius: verticalScale(10),
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: horizontalScale(12),
  },
  categoryText: {
    fontSize: fontScale(10),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  eventPrice: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
    fontWeight: "700",
  },
  eventTitle: {
    fontSize: fontScale(14),
    fontFamily: fonts.Bold,
    color: colors.white,
    lineHeight: fontScale(18),
    marginBottom: verticalScale(8),
  },
  eventDetails: {
    marginBottom: verticalScale(8),
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: verticalScale(4),
  },
  detailText: {
    fontSize: fontScale(12),
    fontFamily: fonts.Regular,
    color: colors.white,
    marginLeft: horizontalScale(6),
  },
  eventActionButton: {
    position: "absolute",
    bottom: verticalScale(15),
    right: 0,
    width: horizontalScale(20),
    height: verticalScale(20),
    borderRadius: verticalScale(12),
    backgroundColor: colors.violate,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionContainer: {
    marginHorizontal: horizontalScale(10),
    marginBottom: verticalScale(0),
    marginTop: verticalScale(0),
    borderRadius: verticalScale(12),
    padding: verticalScale(16),
  },
  sectionContainerNoBorder: {
    backgroundColor: colors.cardBackground,
    marginHorizontal: horizontalScale(20),
    marginBottom: verticalScale(16),
    borderRadius: verticalScale(12),
    padding: verticalScale(16),
  },
  sectionContainerNoBorderReduced: {
    marginHorizontal: horizontalScale(10),
    marginBottom: verticalScale(2),
    borderRadius: verticalScale(12),
    padding: verticalScale(16),
  },
  sectionDivider: {
    height: 1,
    backgroundColor: colors.gray20,
    marginTop: verticalScale(0),
    marginBottom: verticalScale(8),
    marginHorizontal: horizontalScale(25),
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: verticalScale(8),
  },
  infoLabel: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.textcolor,
  },
  infoValue: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.white,
    textAlign: "right",
    flex: 1,
    marginLeft: horizontalScale(10),
  },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: verticalScale(6),
  },
  priceLabel: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.textcolor,
  },
  priceValue: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  divider: {
    height: 1,
    backgroundColor: colors.gray20,
    marginTop: verticalScale(25),
    marginBottom: verticalScale(0),
  },
  dottedLineContainer: {
    alignItems: "center",
    marginVertical: verticalScale(20),
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: verticalScale(4),
  },
  totalLabel: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
  },
  totalValue: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
    fontWeight: "700",
  },
  paymentMethodRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  paymentMethodLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  paymentMethodText: {
    fontSize: fontScale(16),
    fontFamily: fonts.Medium,
    color: colors.white,
    marginLeft: horizontalScale(12),
  },
  changeText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.violate,
  },
  buttonContainer: {
    paddingHorizontal: horizontalScale(20),
    paddingTop: verticalScale(40),
  },
  confirmButton: {
    backgroundColor: colors.violate,
    width: "100%",
    height: verticalScale(50),
    borderRadius: verticalScale(25),
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.violate,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  promoCodeSection: {
    marginTop: verticalScale(20),
    marginBottom: verticalScale(20),
    paddingHorizontal: horizontalScale(20),
  },
  promoCodeContainer: {
    position: "relative",
    width: horizontalScale(335),
    height: verticalScale(48),
  },
  promoCodeInput: {
    width: "100%",
    height: "100%",
    borderRadius: horizontalScale(90),
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(12),
    paddingRight: horizontalScale(80),
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.white,
    borderWidth: 1,
    borderColor: colors.whiteTransparent,
  },
  applyButton: {
    position: "absolute",
    right: horizontalScale(8),
    top: verticalScale(12),
    width: horizontalScale(66),
    height: verticalScale(24),
    backgroundColor: colors.BtnBackground,
    borderRadius: horizontalScale(90),
    alignItems: "center",
    justifyContent: "center",
  },
  applyButtonText: {
    fontSize: fontScale(12),
    fontWeight: "400",
    fontFamily: fonts.regular,
    color: colors.white,
  },
  textLogoContainer: {
    width: horizontalScale(40),
    height: verticalScale(24),
    backgroundColor: colors.white,
    borderRadius: horizontalScale(4),
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: horizontalScale(8),
  },
  textLogo: {
    fontSize: fontScale(10),
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  mastercardLogo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  mastercardCircle: {
    width: horizontalScale(12),
    height: horizontalScale(12),
    borderRadius: horizontalScale(6),
    marginHorizontal: horizontalScale(-2),
  },
  platformPaymentSection: {
    marginHorizontal: horizontalScale(20),
    marginVertical: verticalScale(16),
  },
  platformPayContainer: {
    marginBottom: verticalScale(12),
  },
  platformPayButton: {
    width: "100%",
    height: verticalScale(50),
  },
  cardPaymentContainer: {
    marginBottom: verticalScale(12),
  },
  cardPaymentButton: {
    width: "100%",
    height: verticalScale(50),
  },
  discountButton: {
    paddingHorizontal: horizontalScale(12),
    paddingVertical: verticalScale(8),
    borderRadius: horizontalScale(20),
    borderWidth: 1,
    borderColor: colors.violate,
    backgroundColor: "transparent",
    marginRight: horizontalScale(8),
    marginBottom: verticalScale(8),
  },
  discountButtonSelected: {
    backgroundColor: colors.violate,
  },
  discountButtonText: {
    fontSize: fontScale(12),
    color: colors.primary_pink,
    fontWeight: "500",
  },
  discountButtonTextSelected: {
    color: colors.white,
  },
  // Promo Code Styles
  sectionTitle: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
    marginBottom: verticalScale(5),
  },
  promoCodeContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: verticalScale(10),
    gap: horizontalScale(8),
  },
  promoCodeInput: {
    flex: 1,
    height: verticalScale(45),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    borderRadius: 8,
    paddingHorizontal: horizontalScale(12),
    fontSize: fontScale(14),
    color: colors.textcolor,
    backgroundColor: colors.white,
  },
  browsePromoCodesButton: {
    backgroundColor: colors.primary_blue,
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(12),
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.purpleBorder,
  },
  browsePromoCodesText: {
    color: colors.white,
    fontSize: fontScale(14),
    fontWeight: "600",
  },
  applyPromoCodeButton: {
    backgroundColor: colors.validationSuccess,
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(12),
    borderRadius: 8,
  },
  applyPromoCodeText: {
    color: colors.white,
    fontSize: fontScale(14),
    fontWeight: "600",
  },
  selectedPromoCodeContainer: {
    // marginTop: verticalScale(10),
    padding: verticalScale(12),
    backgroundColor: colors.backgroundColor,
    borderRadius: verticalScale(22),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    alignSelf: "center",
  },
  selectedPromoCodeText: {
    fontSize: fontScale(14),
    color: colors.violate,
    fontWeight: "500",
    flex: 1,
  },
  removePromoCodeButton: {
    backgroundColor: colors.red,
    paddingHorizontal: horizontalScale(12),
    paddingVertical: verticalScale(6),
    borderRadius: verticalScale(22),
  },
  removePromoCodeText: {
    color: colors.white,
    fontSize: fontScale(12),
    fontWeight: "600",
  },
  // Modal Styles
  modalContainer: {
    flex: 1,
    backgroundColor: colors.backgroundColor,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: horizontalScale(20),
    paddingVertical: verticalScale(15),
    borderBottomWidth: 1,
    borderBottomColor: colors.purpleBorder,
  },
  modalTitle: {
    fontSize: fontScale(18),
    fontFamily: fonts.Bold,
    color: colors.textcolor,
  },
  closeButton: {
    width: horizontalScale(30),
    height: verticalScale(30),
    borderRadius: verticalScale(15),
    backgroundColor: colors.lightGray,
    alignItems: "center",
    justifyContent: "center",
  },
  closeButtonText: {
    fontSize: fontScale(16),
    color: colors.textcolor,
    fontWeight: "bold",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: verticalScale(10),
    fontSize: fontScale(16),
    color: colors.textcolor,
  },
  promoCodeList: {
    padding: horizontalScale(16),
  },
  promoCodeItem: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: horizontalScale(16),
    marginBottom: verticalScale(12),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  promoCodeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(8),
  },
  promoCodeText: {
    fontSize: fontScale(18),
    fontWeight: "bold",
    color: colors.primary_pink,
  },
  discountText: {
    fontSize: fontScale(16),
    fontWeight: "600",
    color: colors.green,
  },
  promoCodeDescription: {
    fontSize: fontScale(14),
    color: colors.textcolor,
    marginBottom: verticalScale(4),
  },
  minAmountText: {
    fontSize: fontScale(12),
    color: colors.gray,
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: verticalScale(50),
  },
  emptyStateText: {
    fontSize: fontScale(16),
    color: colors.gray,
    textAlign: "center",
  },

  promoCodeSectionNew: {
    marginTop: verticalScale(20),
    marginBottom: verticalScale(20),
  },
  promoCodeContainerNew: {
    position: "relative",
    width: horizontalScale(335),
    height: verticalScale(48),
  },
  promoCodeInputNew: {
    width: "100%",
    height: "100%",
    borderRadius: horizontalScale(90),
    paddingHorizontal: horizontalScale(8),
    paddingVertical: verticalScale(6),
    paddingRight: horizontalScale(80),
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.white,
    borderWidth: 1,
    borderColor: colors.whiteTransparent,
    textAlignVertical: "center",
    includeFontPadding: false,
    lineHeight: fontScale(14),
    justifyContent: "center",
    alignItems: "center",
  },
  promoCodeInputNewIOS: {
    width: "100%",
    height: "100%",
    borderRadius: horizontalScale(90),
    paddingHorizontal: horizontalScale(8),
    paddingVertical: verticalScale(8),
    paddingRight: horizontalScale(80),
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.white,
    borderWidth: 1,
    borderColor: colors.whiteTransparent,
    textAlignVertical: "center",
    includeFontPadding: false,
    lineHeight: fontScale(16),
    justifyContent: "center",
    alignItems: "center",
  },
  applyButtonNew: {
    position: "absolute",
    right: horizontalScale(8),
    top: verticalScale(12),
    width: horizontalScale(66),
    height: verticalScale(24),
    backgroundColor: colors.BtnBackground,
    borderRadius: horizontalScale(90),
    alignItems: "center",
    justifyContent: "center",
  },
  browseButtonNew: {
    position: "absolute",
    right: horizontalScale(8),
    top: verticalScale(12),
    width: horizontalScale(140),
    height: verticalScale(30),
    backgroundColor: colors.BtnBackground,
    borderRadius: horizontalScale(90),
    alignItems: "center",
    justifyContent: "center",
  },
  applyButtonTextNew: {
    fontSize: fontScale(12),
    fontWeight: "400",
    fontFamily: fonts.regular,
    color: colors.white,
  },
});
