import { StyleSheet, Platform } from "react-native";
import { colors } from "../../../../utilis/colors";
import { fonts } from "../../../../utilis/fonts";
import {
  fontScale,
  horizontalScale,
  verticalScale,
} from "../../../../utilis/appConstant";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradientContainer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: verticalScale(30),
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: horizontalScale(20),
    paddingTop: verticalScale(10),
    paddingBottom: verticalScale(20),
  },
  backButton: {
    width: horizontalScale(40),
    height: verticalScale(40),
    borderRadius: verticalScale(20),
    backgroundColor: colors.addButtonBackground,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: fontScale(18),
    fontFamily: fonts.Bold,
    color: colors.white,
    textAlign: "center",
  },
  headerSpacer: {
    width: horizontalScale(40),
  },
  eventCard: {
    flexDirection: "row",
    backgroundColor: colors.cardBackground,
    marginHorizontal: horizontalScale(20),
    marginBottom: verticalScale(20),
    borderRadius: verticalScale(16),
    padding: verticalScale(12),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    shadowColor: colors.purpleBorder,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  eventImageContainer: {
    position: "relative",
    marginRight: horizontalScale(12),
  },
  eventImage: {
    width: horizontalScale(100),
    height: verticalScale(80),
    borderRadius: verticalScale(12),
  },
  favoriteButton: {
    position: "absolute",
    top: verticalScale(6),
    left: horizontalScale(6),
    width: horizontalScale(24),
    height: verticalScale(24),
    borderRadius: verticalScale(12),
    backgroundColor: colors.violate,
    alignItems: "center",
    justifyContent: "center",
  },
  eventContent: {
    flex: 1,
    justifyContent: "space-between",
  },
  eventHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: verticalScale(8),
  },
  categoryTag: {
    backgroundColor: colors.categoryBackground,
    height: verticalScale(20),
    borderRadius: verticalScale(10),
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: horizontalScale(12),
  },
  categoryText: {
    fontSize: fontScale(10),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  eventPrice: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
    fontWeight: "700",
  },
  eventTitle: {
    fontSize: fontScale(14),
    fontFamily: fonts.Bold,
    color: colors.white,
    lineHeight: fontScale(18),
    marginBottom: verticalScale(8),
  },
  eventDetails: {
    marginBottom: verticalScale(8),
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: verticalScale(4),
  },
  detailText: {
    fontSize: fontScale(12),
    fontFamily: fonts.Regular,
    color: colors.white,
    marginLeft: horizontalScale(6),
  },
  eventActionButton: {
    position: "absolute",
    bottom: verticalScale(15),
    right: 0,
    width: horizontalScale(20),
    height: verticalScale(20),
    borderRadius: verticalScale(12),
    backgroundColor: colors.violate,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionContainer: {
    marginHorizontal: horizontalScale(10),
    marginBottom: verticalScale(0),
    marginTop: verticalScale(0),
    borderRadius: verticalScale(12),
    padding: verticalScale(16),
  },
  sectionContainerNoBorder: {
    backgroundColor: colors.cardBackground,
    marginHorizontal: horizontalScale(20),
    marginBottom: verticalScale(16),
    borderRadius: verticalScale(12),
    padding: verticalScale(16),
  },
  sectionContainerNoBorderReduced: {
    marginHorizontal: horizontalScale(10),
    marginBottom: verticalScale(2),
    borderRadius: verticalScale(12),
    padding: verticalScale(16),
  },
  sectionDivider: {
    height: 1,
    backgroundColor: colors.gray20,
    marginTop: verticalScale(0),
    marginBottom: verticalScale(8),
    marginHorizontal: horizontalScale(25),
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: verticalScale(8),
  },
  infoLabel: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.textcolor,
  },
  infoValue: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.white,
    textAlign: "right",
    flex: 1,
    marginLeft: horizontalScale(10),
  },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: verticalScale(6),
  },
  priceLabel: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.textcolor,
  },
  priceValue: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  divider: {
    height: 1,
    backgroundColor: colors.gray20,
    marginTop: verticalScale(25),
    marginBottom: verticalScale(0),
  },
  dottedLineContainer: {
    alignItems: "center",
    marginVertical: verticalScale(20),
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: verticalScale(4),
  },
  totalLabel: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
  },
  totalValue: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
    fontWeight: "700",
  },
  paymentMethodRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  paymentMethodLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  paymentMethodText: {
    fontSize: fontScale(16),
    fontFamily: fonts.Medium,
    color: colors.white,
    marginLeft: horizontalScale(12),
  },
  changeText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.violate,
  },
  buttonContainer: {
    paddingHorizontal: horizontalScale(20),
    paddingTop: verticalScale(40),
  },
  confirmButton: {
    backgroundColor: colors.violate,
    width: "100%",
    height: verticalScale(50),
    borderRadius: verticalScale(25),
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.violate,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  promoCodeContainer: {
    paddingHorizontal: horizontalScale(20),
    paddingTop: verticalScale(20),
  },
  promoCodeInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(90),
    borderWidth: 1,
    borderColor: colors.gray20,
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(4),
  },
  promoCodeInput: {
    flex: 1,
    height: verticalScale(50),
    fontSize: fontScale(16),
    fontFamily: fonts.Regular,
    color: colors.white,
    paddingHorizontal: horizontalScale(12),
  },
  applyButton: {
    backgroundColor: colors.violate,
    paddingHorizontal: horizontalScale(20),
    paddingVertical: verticalScale(6),
    borderRadius: verticalScale(20),
    marginLeft: horizontalScale(8),
  },
  applyButtonText: {
    fontSize: fontScale(12),
    fontWeight: "400",
    fontFamily: fonts.Regular,
    color: colors.white,
  },
});
