import { StyleSheet } from "react-native";
import { colors } from "../../utilis/colors";
import { fonts } from "../../utilis/fonts";
import {
  fontScale,
  horizontalScale,
  verticalScale,
} from "../../utilis/appConstant";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: verticalScale(20),
  },
  header: {
    paddingTop: verticalScale(50),
    paddingHorizontal: horizontalScale(20),
  },
  statusBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(10),
  },
  statusIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  skipText: {
    color: colors.white,
    fontWeight: "600",
    fontSize: fontScale(16),
    lineHeight: fontScale(24),
    fontFamily: fonts.semiBold,
  },
  titleSection: {
    paddingHorizontal: horizontalScale(20),
    marginBottom: verticalScale(30),
  },
  title: {
    fontSize: fontScale(24),
    fontFamily: fonts.SemiBold,
    fontWeight: "600",
    color: colors.white,
    lineHeight: fontScale(35),
    letterSpacing: 0,
    marginBottom: verticalScale(8),
  },
  subtitle: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    fontWeight: "400",
    color: colors.white,
    lineHeight: fontScale(20),
    letterSpacing: 0,
  },
  socialSection: {
    paddingHorizontal: horizontalScale(20),
    marginBottom: verticalScale(15),
  },
  socialButton: {
    backgroundColor: colors.white,
    width: horizontalScale(333),
    height: verticalScale(49),
    borderRadius: verticalScale(30),
    marginBottom: verticalScale(15),
    paddingTop: verticalScale(12),
    paddingRight: horizontalScale(66),
    paddingBottom: verticalScale(12),
    paddingLeft: horizontalScale(66),
    borderWidth: 1,
    borderColor: colors.lightGray,
    alignSelf: "center",
  },
  socialButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  appleIcons: {
    fontSize: fontScale(20),
    marginRight: horizontalScale(10),
  },
  socialButtonText: {
    fontSize: fontScale(16),
    lineHeight: fontScale(24),
    fontWeight: "600",
    fontFamily: fonts.semiBold,
    color: colors.darkGray,
  },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: verticalScale(5),
    marginBottom: verticalScale(15),
  },
  dividerLine: {
    flex: 1,
    height: verticalScale(1),
    backgroundColor: colors.disableGray,
    opacity: 0.3,
  },
  dividerText: {
    fontWeight: "500",
    color: colors.white,
    fontSize: fontScale(18),
    fontFamily: fonts.medium,
    marginHorizontal: horizontalScale(15),
  },
  roleSection: {
    paddingHorizontal: horizontalScale(20),
    marginBottom: verticalScale(30),
  },
  sectionTitle: {
    fontSize: fontScale(14),
    fontWeight: "400",
    fontFamily: fonts.Regular,
    color: colors.white,
    marginBottom: verticalScale(10),
  },
  roleOptions: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: horizontalScale(40),
  },
  roleOption: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    padding: verticalScale(10),
  },
  selectedRole: {},
  roleContent: {
    alignItems: "center",
  },
  roleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(12),
  },
  roleIconContainer: {
    width: horizontalScale(42),
    height: verticalScale(42),
    borderRadius: horizontalScale(21),
    borderWidth: 1,
    borderColor: colors.violate,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  selectedIconContainer: {
    borderColor: colors.violate,
    backgroundColor: colors.violate,
  },
  radioButton: {
    width: horizontalScale(16),
    height: verticalScale(16),
    borderRadius: horizontalScale(8),
    borderWidth: 1,
    borderColor: colors.disableGray,
    alignItems: "center",
    justifyContent: "center",
  },
  selectedRadio: {
    borderColor: colors.violate,
  },
  radioInner: {
    width: horizontalScale(8),
    height: verticalScale(8),
    borderRadius: horizontalScale(4),
    backgroundColor: colors.violate,
  },
  roleIcon: {
    width: horizontalScale(22),
    height: verticalScale(22),
    alignItems: "center",
    justifyContent: "center",
  },
  roleText: {
    fontFamily: fonts.Regular,
    fontWeight: "400",
    fontSize: fontScale(14),
    lineHeight: fontScale(18),
    letterSpacing: 0,
    color: colors.white,
  },
  formSection: {
    paddingHorizontal: horizontalScale(20),
    marginBottom: verticalScale(4),
  },
  inputContainer: {
    marginBottom: verticalScale(10),
  },
  customInput: {
    marginBottom: verticalScale(4),
  },
  documentSection: {
    paddingHorizontal: horizontalScale(20),
    marginBottom: verticalScale(30),
  },
  documentUpload: {
    width: horizontalScale(335),
    height: verticalScale(138),
    borderWidth: 1,
    borderColor: colors.whiteTransparent,
    borderStyle: "solid",
    borderRadius: horizontalScale(20),
    paddingTop: verticalScale(14),
    paddingRight: horizontalScale(10),
    paddingBottom: verticalScale(20),
    paddingLeft: horizontalScale(12),
    alignItems: "center",
    alignSelf: "center",
  },
  documentContent: {
    alignItems: "center",
    gap: verticalScale(8),
  },
  documentText: {
    fontSize: fontScale(16),
    fontFamily: fonts.Medium,
    color: colors.white,
    marginBottom: verticalScale(5),
  },
  documentSubtext: {
    fontSize: fontScale(12),
    fontFamily: fonts.Regular,
    color: colors.disableGray,
    marginBottom: verticalScale(15),
  },
  browseButton: {
    width: horizontalScale(98),
    height: verticalScale(31),
    backgroundColor: colors.violate,
    borderRadius: horizontalScale(90),
    paddingTop: verticalScale(6),
    paddingRight: horizontalScale(16),
    paddingBottom: verticalScale(6),
    paddingLeft: horizontalScale(16),
    alignItems: "center",
    justifyContent: "center",
  },
  browseButtonText: {
    fontFamily: fonts.Regular,
    fontWeight: "400",
    fontSize: fontScale(12),
    lineHeight: fontScale(19.2),
    letterSpacing: 0,
    textAlign: "center",
    color: colors.white,
  },
  buttonSection: {
    paddingHorizontal: horizontalScale(20),
    paddingBottom: verticalScale(10),
  },
  signUpButton: {
    marginBottom: verticalScale(20),
  },
  loginLink: {
    alignItems: "center",
  },
  loginText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    fontWeight: "400",
    color: colors.white,
    lineHeight: fontScale(20),
    letterSpacing: 0,
    textAlign: "center",
  },
  loginLinkText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    fontWeight: "400",
    color: colors.violate,
    lineHeight: fontScale(20),
    letterSpacing: 0,
    textAlign: "center",
  },
  passwordValidationContainer: {
    marginTop: 0,
    marginBottom: verticalScale(16),
    paddingHorizontal: horizontalScale(4),
  },
  passwordValidationTitle: {
    fontSize: fontScale(12),
    fontFamily: fonts.medium,
    fontWeight: "400",
    color: colors.white,
    marginBottom: verticalScale(8),
    lineHeight: fontScale(16),
    letterSpacing: 0,
  },
  validationList: {
    gap: verticalScale(4),
  },
  validationItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: verticalScale(4),
  },
  validationText: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    fontWeight: "400",
    fontStyle: "normal",
    color: colors.disableGray,
    lineHeight: fontScale(16),
    letterSpacing: 0,
    flex: 1,
    flexWrap: "wrap",
  },
  validationTextValid: {
    color: colors.green,
  },
  selectedFileContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: verticalScale(10),
  },
  selectedFileName: {
    fontSize: fontScale(14),
    fontFamily: fonts.regular,
    fontWeight: "500",
    color: colors.white,
    textAlign: "center",
    marginBottom: verticalScale(4),
  },
  selectedFileSize: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    fontWeight: "400",
    color: colors.disableGray,
    textAlign: "center",
    marginBottom: verticalScale(12),
  },
  changeFileButton: {
    backgroundColor: colors.whiteTransparentLight,
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(8),
    borderRadius: horizontalScale(20),
    borderWidth: 1,
    borderColor: colors.whiteTransparentMedium,
  },
  changeFileButtonText: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    fontWeight: "500",
    color: colors.white,
  },
});