import { StyleSheet, Platform } from "react-native";
import { colors } from "../../utilis/colors";
import { fonts } from "../../utilis/fonts";
import {
  fontScale,
  horizontalScale,
  verticalScale,
} from "../../utilis/appConstant";

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  statusBar: {
    height: verticalScale(44),
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: horizontalScale(20),
    marginBottom: verticalScale(20),
  },
  title: {
    fontSize: fontScale(20),
    fontFamily: fonts.semiBold,
    color: colors.white,
    textAlign: "center",
    flex: 1,
    lineHeight: fontScale(24),
  },
  placeholder: {
    width: horizontalScale(44),
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: verticalScale(100),
  },
  eventCard: {
    backgroundColor: colors.cardBackground,
    width: horizontalScale(334),
    height: verticalScale(120),
    borderRadius: verticalScale(16),
    borderWidth: verticalScale(1),
    borderColor: colors.purpleBorder,
    marginHorizontal: horizontalScale(20),
    marginBottom: verticalScale(30),
    shadowColor: colors.purpleBorder,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: verticalScale(0.1),
    shadowRadius: 8,
    elevation: 4,
  },
  cardTopSection: {
    flexDirection: "row",
    padding: verticalScale(12),
    height: verticalScale(120),
  },
  imageContainer: {
    position: "relative",
    marginRight: horizontalScale(15),
  },
  eventImage: {
    width: horizontalScale(120),
    height: verticalScale(100),
    borderRadius: verticalScale(14),
  },
  favoriteButton: {
    position: "absolute",
    top: verticalScale(8),
    left: horizontalScale(8),
    alignItems: "center",
    justifyContent: "center",
  },
  eventContent: {
    flex: 1,
    justifyContent: "center",
    marginTop: verticalScale(8),
  },
  eventHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  categoryTag: {
    backgroundColor: colors.categoryBackground,
    height: verticalScale(16),
    width: horizontalScale(48),
    borderRadius: verticalScale(12),
    alignSelf: "flex-start",
    alignItems: "center",
    justifyContent: "center",
  },
  categoryText: {
    fontSize: fontScale(8),
    fontWeight: "400",
    fontFamily: fonts.regular,
    color: colors.white,
    lineHeight: fontScale(16),
  },
  priceText: {
    fontSize: fontScale(16),
    fontFamily: fonts.ExtraBold,
    color: colors.white,
    fontWeight: "800",
    lineHeight: fontScale(20),
  },
  eventName: {
    fontSize: fontScale(13),
    fontWeight: "700",
    fontFamily: fonts.Bold,
    color: colors.white,
    marginBottom: verticalScale(5),
    lineHeight: fontScale(16),
  },
  detailsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: verticalScale(6),
  },
  detailText: {
    fontSize: fontScale(12),
    fontWeight: "400",
    fontFamily: fonts.Regular,
    color: colors.white,
    marginLeft: horizontalScale(6),
    lineHeight: fontScale(16),
  },
  actionButton: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: horizontalScale(24),
    height: verticalScale(24),
    borderRadius: verticalScale(12),
    backgroundColor: colors.violate,
    justifyContent: "center",
    alignItems: "center",
  },
  reviewSection: {
    paddingHorizontal: horizontalScale(20),
  },
  experienceTitle: {
    fontSize: fontScale(20),
    fontWeight: "600",
    fontFamily: fonts.semiBold,
    color: colors.white,
    textAlign: "center",
    marginBottom: verticalScale(20),
    lineHeight: fontScale(24),
  },
  separator: {
    width: horizontalScale(335),
    height: 0,
    opacity: 0.2,
    borderWidth: 1,
    borderColor: colors.whiteSeperatorLight,
    marginBottom: verticalScale(15),
  },
  separatorsecond: {
    width: horizontalScale(335),
    height: 0,
    opacity: 0.2,
    borderWidth: 1,
    borderColor: colors.whiteSeperatorLight,
    marginTop: verticalScale(15),
  },
  ratingLabel: {
    fontSize: fontScale(14),
    fontWeight: "400",
    fontFamily: fonts.regular,
    color: colors.white,
    marginBottom: verticalScale(10),
    textAlign: "center",
    lineHeight: fontScale(16),
  },
  detailsLabel: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.white,
    marginTop: verticalScale(15),
    marginBottom: verticalScale(6),
    lineHeight: fontScale(16),
  },
  reviewInput: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: colors.whiteTransparentMedium,
    borderRadius: verticalScale(20),
    width: horizontalScale(335),
    height: verticalScale(110),
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.textcolor,
    minHeight: verticalScale(100),
    textAlignVertical: "top",
    paddingHorizontal: horizontalScale(15),
    paddingTop: verticalScale(15),
    paddingBottom: verticalScale(15),
    paddingLeft: horizontalScale(15),
    paddingRight: horizontalScale(15),
  },
  reviewInputPlaceholder: {
    color: colors.textcolor,
    fontSize: fontScale(14),
    lineHeight: fontScale(16),
    fontWeight: "300",
    fontFamily: fonts.light,
  },
  submitContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.gradient_dark_purple,
    paddingHorizontal: horizontalScale(20),
    paddingVertical: verticalScale(20),
    paddingBottom: verticalScale(Platform.OS === "ios" ? 34 : 20),
  },
  submitButton: {
    marginBottom: 0,
  },
  submitButtonContainer: {
    marginTop: verticalScale(20),
    marginBottom: verticalScale(20),
  },
  customButton: {
    width: horizontalScale(48),
    height: verticalScale(16),
    borderRadius: verticalScale(90),
    backgroundColor: colors.violate,
  },
});

export default styles;
