import { StyleSheet } from "react-native";
import { colors } from "../utilis/colors";
import {
  verticalScale,
  horizontalScale,
  fontScale,
} from "../utilis/appConstant";
import { fonts } from "../utilis/fonts";

export const styles = StyleSheet.create({
  container: {
    // height: verticalScale(350),
    borderRadius: horizontalScale(20),
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.violate,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(20),
    width: "91%",
    paddingTop: verticalScale(25),
  },
  monthYearText: {
    fontSize: fontScale(24),
    fontWeight: "700",
    fontFamily: fonts.Bold,
    color: colors.white,
  },
  navigationButtons: {
    flexDirection: "row",
    gap: horizontalScale(8),
  },
  navButton: {
    width: horizontalScale(28),
    height: verticalScale(28),
    justifyContent: "center",
    alignItems: "center",
  },
  daysOfWeekContainer: {
    flexDirection: "row",
    marginBottom: verticalScale(8),
    width: "100%",
  },
  dayOfWeekText: {
    fontSize: fontScale(10.39),
    fontWeight: "500",
    fontFamily: fonts.Medium,
    color: colors.white,
    textAlign: "center",
    flex: 1,
    minWidth: 0,
  },
  calendarContainer: {
    flexDirection: "column",
    width: "100%",
    paddingHorizontal: 0,
    alignItems: "stretch",
  },
  weekRow: {
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "flex-start",
    width: "100%",
    paddingHorizontal: 0,
  },
  dayCell: {
    height: verticalScale(41.55038833618164),
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    borderRadius: 0,
    marginHorizontal: 0,
    marginVertical: 0,
    flex: 1,
    minWidth: 0,
    maxWidth: "14.28%", // 100% / 7 = 14.28%
  },
  dayText: {
    fontSize: fontScale(13.85),
    color: colors.white,
    fontWeight: "500",
    fontFamily: fonts.Medium,
    textAlign: "center",
    lineHeight: fontScale(13.85),
    width: "100%",
    textAlignVertical: "center",
  },
  rangeDay: {
    backgroundColor: colors.white,
    borderRadius: 0,
    marginHorizontal: 0,
    marginVertical: 0,
    height: verticalScale(41.55038833618164),
    flex: 1,
  },
  rangeDayText: {
    color: colors.black,
    fontWeight: "500",
    fontFamily: fonts.Medium,
    fontSize: fontScale(13.85),
    textAlign: "center",
    width: "100%",
    textAlignVertical: "center",
  },
  selectedDay: {
    backgroundColor: colors.violate,
    borderRadius: horizontalScale(20),
    height: verticalScale(41.55038833618164),
    marginHorizontal: 0,
    marginVertical: 0,
    flex: 1,
  },
  selectedDayText: {
    color: colors.white,
    fontWeight: "600",
    fontFamily: fonts.SemiBold,
    fontSize: fontScale(13.85),
    textAlign: "center",
    width: "100%",
    textAlignVertical: "center",
  },
  // Capsule styling for date range
  startDateCapsule: {
    backgroundColor: colors.violate,
    borderRadius: horizontalScale(20),
    height: verticalScale(41.55038833618164),
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    marginRight: 0,
    marginLeft: 0,
    marginVertical: 0,
    flex: 1,
  },
  endDateCapsule: {
    backgroundColor: colors.violate,
    borderRadius: horizontalScale(20),
    height: verticalScale(41.55038833618164),
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    marginLeft: 0,
    marginRight: 0,
    marginVertical: 0,
    flex: 1,
  },
  singleDateCapsule: {
    backgroundColor: colors.violate,
    borderRadius: horizontalScale(20),
    height: verticalScale(41.55038833618164),
    marginLeft: 0,
    marginRight: 0,
    marginVertical: 0,
    flex: 1,
  },
  middleDateCapsule: {
    backgroundColor: colors.white,
    borderRadius: 0,
    height: verticalScale(41.55038833618164),
    marginVertical: 0,
    marginHorizontal: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    flex: 1,
  },
  todayDay: {
    // No special background for today
  },
  todayDayText: {
    color: colors.validationSuccess,
    fontWeight: "500",
    fontFamily: fonts.Medium,
    fontSize: fontScale(13.85),
    textAlign: "center",
    width: "100%",
    textAlignVertical: "center",
  },
  // Disabled date styling
  disabledDayText: {
    color: colors.disabledDayText,
    textDecorationLine: "line-through",
    fontWeight: "500",
    fontFamily: fonts.Medium,
    fontSize: fontScale(13.85),
    textAlign: "center",
    width: "100%",
    textAlignVertical: "center",
  },
  // Booked date styling - individual round shapes
  bookedDay: {
    backgroundColor: colors.gray100 || "#9CA3AF",
    borderRadius: horizontalScale(20),
    height: verticalScale(41.55038833618164),
    width: verticalScale(41.55038833618164),
    opacity: 0.8,
    marginHorizontal: 2,
    marginVertical: 2,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bookedDayText: {
    color: colors.white,
    fontWeight: "500",
    fontFamily: fonts.Medium,
    fontSize: fontScale(13.85),
    textAlign: "center",
    textAlignVertical: "center",
  },
  // Booked date range styling (joined red dates)
  bookedStartCapsule: {
    backgroundColor: colors.gray100 || "#FF6B6B",
    borderRadius: horizontalScale(20),
    height: verticalScale(41.55038833618164),
    flex: 1,
    opacity: 0.8,
  },
  bookedEndCapsule: {
    backgroundColor: colors.gray100 || "#FF6B6B",
    borderRadius: horizontalScale(22),
    height: verticalScale(41.55038833618164),
    opacity: 0.8,
  },
  bookedMiddleCapsule: {
    backgroundColor: colors.gray100 || "#FF6B6B",
    borderRadius: 0,
    height: verticalScale(41.55038833618164),
    marginVertical: 0,
    marginHorizontal: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    flex: 1,
    opacity: 0.8,
  },
  // Square booked dates within selected range
  bookedInRange: {
    backgroundColor: colors.gray100 || "#FF6B6B",
    borderRadius: 0,
    height: verticalScale(41.55038833618164),
    marginVertical: 0,
    marginHorizontal: 0,
    flex: 1,
    opacity: 0.8,
  },
  bookedInRangeStart: {
    backgroundColor: colors.gray100 || "#FF6B6B",
    borderRadius: 0,
    height: verticalScale(41.55038833618164),
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    marginRight: 0,
    marginLeft: 0,
    marginVertical: 0,
    flex: 1,
    opacity: 0.8,
  },
  bookedInRangeEnd: {
    backgroundColor: colors.gray100 || "#FF6B6B",
    borderRadius: 0,
    height: verticalScale(41.55038833618164),
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    marginLeft: 0,
    marginRight: 0,
    marginVertical: 0,
    flex: 1,
    opacity: 0.8,
  },
  bookedInRangeMiddle: {
    backgroundColor: colors.gray100 || "#FF6B6B",
    borderRadius: 0,
    height: verticalScale(41.55038833618164),
    marginVertical: 0,
    marginHorizontal: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    flex: 1,
    opacity: 0.8,
  },
  // Enhanced hover/press states
  dayCellPressed: {
    opacity: 0.7,
    transform: [{ scale: 0.95 }],
  },
  // Empty cell styling
  emptyCell: {
    backgroundColor: "transparent",
    opacity: 0,
  },
  // Better range visualization
  rangeIndicator: {
    position: "absolute",
    top: 0,
    bottom: 0,
    backgroundColor: colors.white,
    opacity: 0.3,
  },
});
