import { StyleSheet } from "react-native";
import { colors } from "../utilis/colors";
import {
  fontScale,
  horizontalScale,
  verticalScale,
} from "../utilis/appConstant";
import { fonts } from "../utilis/fonts";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: colors.overlayBackground,
    justifyContent: "flex-end",
  },
  popupContainer: {
    width: "100%",
    height: verticalScale(290),
    backgroundColor: colors.cardBackground,
    borderTopLeftRadius: horizontalScale(30),
    borderTopRightRadius: horizontalScale(30),
    borderBottomLeftRadius: horizontalScale(60),
    borderBottomRightRadius: horizontalScale(60),
    borderWidth: verticalScale(1),
    borderColor: colors.BtnBackground,
    paddingHorizontal: horizontalScale(24),
    paddingTop: verticalScale(12),
    paddingBottom: verticalScale(34),
    position: "absolute",
    alignSelf: "center",
    marginHorizontal: horizontalScale(20),
  },
  handle: {
    width: horizontalScale(40),
    height: 4,
    backgroundColor: colors.gradient_light_purple,
    borderRadius: horizontalScale(2),
    alignSelf: "center",
    marginBottom: verticalScale(24),
  },
  topLine: {
    width: horizontalScale(70),
    height: verticalScale(3),
    backgroundColor: colors.BtnBackground,
    borderRadius: horizontalScale(100),
    opacity: 0.4,
    alignSelf: "center",
    marginBottom: verticalScale(8),
  },
  title: {
    fontSize: fontScale(22),
    fontWeight: "600",
    fontFamily: fonts.semiBold,
    color: colors.whiteLight,
    textAlign: "center",
    marginBottom: verticalScale(16),
  },
  message: {
    fontSize: fontScale(14),
    fontWeight: "400",
    fontFamily: fonts.regular,
    color: colors.textcolor,
    textAlign: "center",
    lineHeight: fontScale(22),
    marginBottom: verticalScale(32),
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  cancelButton: {
    width: horizontalScale(156),
    height: verticalScale(50),
    backgroundColor: colors.transparent,
    borderWidth: verticalScale(1),
    borderColor: colors.BtnBackground,
    borderRadius: horizontalScale(99),
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButtonText: {
    color: colors.white,
    fontSize: fontScale(16),
    lineHeight: fontScale(20),
    fontFamily: fonts.semiBold,
    fontWeight: "600",
  },
  logoutButton: {
    width: horizontalScale(156),
    height: verticalScale(50),
    backgroundColor: colors.BtnBackground,
    borderRadius: horizontalScale(99),
    alignItems: "center",
    justifyContent: "center",
  },
  logoutButtonText: {
    color: colors.white,
    lineHeight: fontScale(24),
    fontSize: fontScale(16),
    fontFamily: fonts.semiBold,
    fontWeight: "600",
  },
});
