import { Platform, StyleSheet } from 'react-native';
import { colors } from '../../../../utilis/colors';
import { fonts } from '../../../../utilis/fonts';
import { fontScale, horizontalScale, verticalScale } from '../../../../utilis/appConstant';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gradient_dark_purple,
  },
  headerContainer: {
    height: verticalScale(371),
    position: 'relative',
    marginTop: verticalScale(-60),
  },
  headerImage: {
    width: '100%',
    height: '100%',
  },
  imageOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  topNavigation: {
    position: 'absolute',
    top: verticalScale(120),
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: horizontalScale(20),
    zIndex: 10,
  },
  backButton: {
    width: horizontalScale(40),
    height: verticalScale(40),
    borderRadius: verticalScale(20),
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: Platform.OS === 'ios' ? verticalScale(-90) : verticalScale(-30),
  },
  rightIcons: {
    flexDirection: 'column',
  },
  iconButton: {
    width: horizontalScale(40),
    height: verticalScale(40),
    borderRadius: verticalScale(20),
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: verticalScale(12),
  },
  eventCard: {
    backgroundColor: 'transparent', // Make transparent since it's inside eventCardNew
    marginTop: 0, // Remove margin since it's inside the scrollable container
  },
  eventCardNew: {
    borderWidth: 1,
    borderColor: colors.violate,
    backgroundColor: colors.backgroundColor,
    borderRadius: verticalScale(16),
    marginHorizontal: horizontalScale(15),
    shadowColor: colors.white,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    height: verticalScale(500),
    marginTop: verticalScale(-140),
    overflow: 'hidden', // Ensure content doesn't overflow the rounded corners
    position: 'relative', // For loading overlay positioning
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    borderRadius: verticalScale(16),
  },
  loadingText: {
    fontSize: fontScale(16),
    fontFamily: fonts.Medium,
    color: colors.white,
    marginTop: verticalScale(12),
  },
  eventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(12),
  },
  categoryTag: {
    backgroundColor: colors.vilate20,
    paddingHorizontal: horizontalScale(12),
    paddingVertical: verticalScale(4),
    borderRadius: verticalScale(12),
  },
  categoryText: {
    fontSize: fontScale(12),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: horizontalScale(4),
  },
  ratingText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Bold,
    color: colors.white,
  },
  eventTitle: {
    fontSize: fontScale(20),
    fontFamily: fonts.Bold,
    color: colors.white,
    lineHeight: fontScale(26),
    marginBottom: verticalScale(12),
    fontWeight: '700',
  },
  eventDetails: {
    gap: verticalScale(8),
    marginBottom: verticalScale(16),
    //flexDirection: 'row',
    justifyContent: 'space-between',
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: horizontalScale(8),
  },
  detailText: {
    fontSize: fontScale(12),
    fontFamily: fonts.Medium,
    color: colors.white,
    fontWeight: '400',
  },
  aboutSection: {
    marginTop: verticalScale(8),
  },
  aboutTitle: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
    marginBottom: verticalScale(8),
    fontWeight: '700',
  },
  aboutText: {
    fontSize: fontScale(12),
    fontFamily: fonts.Regular,
    color: colors.white,
    lineHeight: fontScale(16),
    fontWeight: '400',
  },
  content: {
    flex: 1,
    paddingBottom: verticalScale(20), // Reduced padding for scroll inside card
    paddingTop: verticalScale(20), // Add top padding
    paddingHorizontal: horizontalScale(20), // Add horizontal padding
  },
  section: {
    marginBottom: verticalScale(24),
    marginTop: verticalScale(20),
  },
  sectionTitle: {
    fontSize: fontScale(18),
    fontFamily: fonts.Bold,
    color: colors.white,
    //marginBottom: verticalScale(16),
  },
  loungesContainer: {
    flexDirection: 'row',
    gap: horizontalScale(16),
  },
  loungeCard: {
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(12),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    width: horizontalScale(280), // Fixed width for horizontal scroll
    flexShrink: 0, // Prevent shrinking
  },
  ticketCard: {
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(12),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    width: horizontalScale(173), // Fixed width for horizontal scroll
    flexShrink: 0, // Prevent shrinking
  },
  loungeCardSelected: {
    borderColor: colors.violate,
    borderWidth: 2,
  },
  loungeImage: {
    width: '100%',
    height: verticalScale(120),
  },
  loungeContent: {
    padding: horizontalScale(16),
  },
  loungeName: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
    marginBottom: verticalScale(4),
  },
  loungeTitle: {
    fontSize: fontScale(12),
    fontFamily: fonts.Regular,
    color: colors.textcolor,
    marginBottom: verticalScale(2),
  },
  loungeDetails: {
    fontSize: fontScale(12),
    fontFamily: fonts.Regular,
    color: colors.white,
    marginBottom: verticalScale(12),
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: horizontalScale(8),
    marginBottom: verticalScale(12),
  },
  originalPrice: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.lightGray,
    textDecorationLine: 'line-through',
  },
  discountedPrice: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
  },
  selectButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.violate,
    paddingVertical: verticalScale(8),
    paddingHorizontal: horizontalScale(16),
    borderRadius: verticalScale(20),
    alignSelf: 'flex-start',
  },
  selectButtonSelected: {
    backgroundColor: colors.violate,
  },
  selectButtonText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.violate,
  },
  selectButtonTextSelected: {
    color: colors.white,
  },
  organizationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBackground,
    //padding: horizontalScale(16),
    borderRadius: verticalScale(12),
    marginTop: verticalScale(12),
  
  },
  organizerAvatar: {
    width: horizontalScale(50),
    height: verticalScale(50),
    borderRadius: verticalScale(25),
    marginRight: horizontalScale(12),
    borderWidth: 2,
    borderColor: colors.violate,
  },
  organizerInfo: {
    flex: 1,
  },
  organizerName: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
    marginBottom: verticalScale(4),
  },
  organizerRole: {
    fontSize: fontScale(12),
    fontFamily: fonts.Regular,
    color: colors.lightGray,
  },
  contactIcons: {
    flexDirection: 'row',
    gap: horizontalScale(12),
  },
  contactButton: {
    width: horizontalScale(40),
    height: verticalScale(40),
    borderRadius: verticalScale(20),
    backgroundColor: colors.violate + '20',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addressCard: {
    backgroundColor: colors.cardBackground,
    padding: horizontalScale(16),
    borderRadius: verticalScale(12),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    marginBottom: verticalScale(12),
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: horizontalScale(8),
    marginBottom: verticalScale(8),
  },
  addressText: {
    fontSize: fontScale(12),
    fontFamily: fonts.Regular,
    color: colors.white,
    flex: 1,
    fontWeight: '400',
    lineHeight: fontScale(16),
  },
  mapButton: {
    alignSelf: 'flex-end',
  },
  mapButtonText: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.violate,
    textDecorationLine: 'underline',
  },
  mapImage: {
    width: '100%',
    height: '100%',
  },
  facilitiesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: horizontalScale(12),
    marginTop: verticalScale(18),
  },
  facilityButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.violate + '20',
    paddingVertical: verticalScale(8),
    paddingHorizontal: horizontalScale(12),
    borderRadius: verticalScale(20),
    borderWidth: 1,
    borderColor: colors.violate,
    gap: horizontalScale(6),
  },
  facilityText: {
    fontSize: fontScale(12),
    fontFamily: fonts.Medium,
    color: colors.white,
  },
  facilityButtonSelected: {
    backgroundColor: colors.violate,
    borderColor: colors.violate,
  },
  facilityTextSelected: {
    color: colors.white,
    fontWeight: 'bold',
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.cardBackground,
    paddingHorizontal: horizontalScale(20),
    paddingVertical: verticalScale(16),
    marginHorizontal: Platform.OS === 'ios' ? horizontalScale(0) : horizontalScale(15),
    borderTopWidth: 1,
    borderRadius: verticalScale(60),
    shadowColor: colors.violate,
    shadowOffset: {
      width: 0,
      height: -4, // Negative value creates shadow on top
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 10, // For Android
    marginBottom: Platform.OS === 'ios' ? verticalScale(0) : verticalScale(15),
  },
  priceSection: {
    flex: 1,
  },
  totalPriceLabel: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    color: colors.textcolor,
    marginBottom: verticalScale(4),
  },
  totalPriceValue: {
    fontSize: fontScale(24),
    fontFamily: fonts.Bold,
    color: colors.white,
  },
  bookNowButton: {
    backgroundColor: colors.violate,
    paddingVertical: verticalScale(16),
    paddingHorizontal: horizontalScale(32),
    borderRadius: verticalScale(25),
  },
  bookNowButtonDisabled: {
    backgroundColor: colors.lightGray,
    opacity: 0.6,
  },
  bookNowText: {
    fontSize: fontScale(16),
    fontFamily: fonts.Bold,
    color: colors.white,
  },
  mapContainer: {
    height: verticalScale(200),
    borderRadius: verticalScale(12),
    overflow: 'hidden',
    marginTop: verticalScale(12),
  },
  map: {
    width: '100%',
    height: '100%',
  },
  mapPin: {
    width: horizontalScale(40),
    height: verticalScale(40),
    borderRadius: verticalScale(20),
    backgroundColor: colors.violate,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.white,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
  // Coming Soon Dialog Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: horizontalScale(20),
  },
  comingSoonDialog: {
    backgroundColor: colors.white,
    borderRadius: verticalScale(16),
    padding: verticalScale(24),
    width: '100%',
    maxWidth: horizontalScale(320),
    shadowColor: colors.white,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  dialogHeader: {
    alignItems: 'center',
    marginBottom: verticalScale(16),
  },
  dialogTitle: {
    fontSize: fontScale(24),
    fontFamily: fonts.bold,
    color: colors.violate,
    textAlign: 'center',
  },
  dialogContent: {
    marginBottom: verticalScale(24),
  },
  dialogMessage: {
    fontSize: fontScale(16),
    fontFamily: fonts.regular,
    color: colors.white,
    textAlign: 'center',
    lineHeight: fontScale(22),
  },
  dialogActions: {
    alignItems: 'center',
  },
  dialogButton: {
    backgroundColor: colors.violate,
    paddingHorizontal: horizontalScale(32),
    paddingVertical: verticalScale(12),
    borderRadius: verticalScale(32),
    minWidth: horizontalScale(120),
  },
  dialogButtonText: {
    fontSize: fontScale(16),
    fontFamily: fonts.semiBold,
    color: colors.white,
    textAlign: 'center',

  },

  // Edit Detail Screen Styles
  formContainer: {
    flex: 1,
    paddingHorizontal: horizontalScale(20),
    paddingTop: verticalScale(20),
  },
  formSection: {
    marginBottom: verticalScale(30),
  },
  sectionTitle: {
    fontSize: fontScale(18),
    fontFamily: fonts.semiBold,
    color: colors.white,
    marginBottom: verticalScale(15),
  },
  inputContainer: {
    marginBottom: verticalScale(20),
  },
  inputLabel: {
    fontSize: fontScale(14),
    fontFamily: fonts.medium,
    color: colors.white,
    marginBottom: verticalScale(8),
  },
  textInput: {
    borderWidth: 1,
    borderColor: colors.gray,
    borderRadius: verticalScale(8),
    paddingHorizontal: horizontalScale(15),
    paddingVertical: verticalScale(12),
    fontSize: fontScale(14),
    fontFamily: fonts.regular,
    color: colors.white,
    backgroundColor: colors.white,
  },
  textArea: {
    height: verticalScale(100),
    textAlignVertical: 'top',
  },
  rowContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  saveButton: {
    padding: horizontalScale(8),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  loadingText: {
    fontSize: fontScale(16),
    fontFamily: fonts.medium,
    color: colors.white,
    marginTop: verticalScale(10),
  },

  // Edit Button Styles
  editButtonContainer: {
    position: 'absolute',
    bottom: verticalScale(20),
    left: horizontalScale(20),
    right: horizontalScale(20),
    zIndex: 1000,
  },
  editButton: {
    backgroundColor: colors.violate,
    paddingVertical: verticalScale(15),
    paddingHorizontal: horizontalScale(20),
    borderRadius: verticalScale(25),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.white,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  editButtonText: {
    fontSize: fontScale(16),
    fontFamily: fonts.semiBold,
    color: colors.white,
  },

  // Add Event Style Matching
  container: {
    flex: 1,
    backgroundColor: colors.gradient_dark_purple,
  },
  gradientContainer: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: horizontalScale(20),
    paddingTop: verticalScale(10),
    paddingBottom: verticalScale(20),
  },
  headerTitle: {
    color: colors.white,
    fontSize: fontScale(20),
    fontWeight: "600",
    fontFamily: fonts.semiBold,
    flex: 1,
    textAlign: "center",
  },
  headerRight: {
    width: horizontalScale(30),
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: horizontalScale(20),
    paddingVertical: verticalScale(20),
  },
  formElement: {
    marginBottom: verticalScale(16),
    marginTop: verticalScale(16),
  },
  timeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: verticalScale(15),
  },
  timeInputContainer: {
    flex: 1,
    marginHorizontal: horizontalScale(5),
    position: "relative",
  },
  timeInputLabel: {
    color: colors.white,
    fontSize: fontScale(14),
    fontFamily: fonts.medium,
    marginBottom: verticalScale(8),
  },
  timeInputButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.transparent,
    borderRadius: 90,
    borderWidth: 1,
    borderColor: colors.whiteTransparentMedium,
    paddingHorizontal: horizontalScale(15),
    paddingVertical: verticalScale(15),
    minHeight: verticalScale(50),
  },
  timeInputText: {
    color: colors.white,
    fontSize: fontScale(15),
    fontFamily: fonts.regular,
    flex: 1,
  },
  saveButton: {
    backgroundColor: colors.violate,
    borderRadius: verticalScale(25),
    paddingVertical: verticalScale(15),
    alignItems: "center",
    justifyContent: "center",
    marginTop: verticalScale(20),
  },
  timePickerModal: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  timePickerContainer: {
    backgroundColor: colors.white,
    borderTopLeftRadius: verticalScale(20),
    borderTopRightRadius: verticalScale(20),
    paddingHorizontal: horizontalScale(20),
    paddingVertical: verticalScale(30),
    maxHeight: "70%",
  },
  timePickerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(20),
  },
  timePickerTitle: {
    fontSize: fontScale(18),
    fontFamily: fonts.semiBold,
    color: colors.white,
  },
  timePickerCloseButton: {
    width: horizontalScale(30),
    height: verticalScale(30),
    borderRadius: verticalScale(15),
    backgroundColor: colors.gray,
    alignItems: "center",
    justifyContent: "center",
  },
  timePickerCloseText: {
    fontSize: fontScale(16),
    color: colors.white,
    fontFamily: fonts.semiBold,
  },
  timeDisplayContainer: {
    alignItems: "center",
    marginBottom: verticalScale(20),
  },
  timeDisplayText: {
    fontSize: fontScale(24),
    fontFamily: fonts.semiBold,
    color: colors.white,
  },
  timePickerButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: verticalScale(20),
  },
  timePickerCancelButton: {
    flex: 1,
    backgroundColor: colors.gray,
    paddingVertical: verticalScale(12),
    borderRadius: verticalScale(8),
    alignItems: "center",
    marginRight: horizontalScale(10),
  },
  timePickerCancelText: {
    color: colors.white,
    fontSize: fontScale(16),
    fontFamily: fonts.semiBold,
  },
  timePickerConfirmButton: {
    flex: 1,
    backgroundColor: colors.violate,
    paddingVertical: verticalScale(12),
    borderRadius: verticalScale(8),
    alignItems: "center",
    marginLeft: horizontalScale(10),
  },
  timePickerConfirmText: {
    color: colors.white,
    fontSize: fontScale(16),
    fontFamily: fonts.semiBold,
  },

  // Additional styles for Add Event matching
  label: {
    color: colors.white,
    fontSize: fontScale(14),
    fontFamily: fonts.medium,
    marginBottom: verticalScale(8),
  },
  timeInputPlaceholder: {
    color: colors.textColor,
    fontSize: fontScale(15),
    fontFamily: fonts.regular,
    flex: 1,
  },
  addressContainer: {
    marginTop: verticalScale(8),
  },
  addressInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.transparent,
    borderRadius: 90,
    borderWidth: 1,
    borderColor: colors.whiteTransparentMedium,
    paddingHorizontal: horizontalScale(15),
    paddingVertical: verticalScale(15),
    minHeight: verticalScale(50),
  },
  addressInput: {
    flex: 1,
    color: colors.white,
    fontSize: fontScale(15),
    fontFamily: fonts.regular,
    textAlignVertical: 'top',
  },
  locationIconContainer: {
    marginLeft: horizontalScale(10),
  },
  errorText: {
    color: colors.red,
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    marginTop: verticalScale(5),
  },
  datePickerWrapper: {
    marginTop: verticalScale(8),
  },
  toggleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: verticalScale(8),
  },
  toggleLabel: {
    color: colors.white,
    fontSize: fontScale(14),
    fontFamily: fonts.medium,
    flex: 1,
  },
  toggleButton: {
    backgroundColor: colors.transparent,
    borderRadius: 90,
    borderWidth: 1,
    borderColor: colors.whiteTransparentMedium,
    paddingHorizontal: horizontalScale(20),
    paddingVertical: verticalScale(8),
  },
  toggleButtonActive: {
    backgroundColor: colors.violate,
    borderColor: colors.violate,
  },
  toggleButtonText: {
    color: colors.white,
    fontSize: fontScale(14),
    fontFamily: fonts.medium,
  },
  toggleButtonTextActive: {
    color: colors.white,
  },
  addNewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.transparent,
    borderRadius: 90,
    borderWidth: 2,
    borderColor: colors.violate,
    borderStyle: 'dashed',
    paddingVertical: verticalScale(15),
    paddingHorizontal: horizontalScale(20),
    marginTop: verticalScale(10),
  },
  addNewButtonText: {
    color: colors.violate,
    fontSize: fontScale(16),
    fontFamily: fonts.semiBold,
    marginLeft: horizontalScale(10),
  },
  sectionLabel: {
    color: colors.white,
    fontSize: fontScale(16),
    fontFamily: fonts.semiBold,
    marginBottom: verticalScale(15),
  },
  uploadPhotosRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: verticalScale(10),
  },
  imageContainer: {
    position: 'relative',
    width: horizontalScale(100),
    height: verticalScale(100),
  },
  imageUploadBox: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.transparent,
    borderRadius: verticalScale(8),
    borderWidth: 1,
    borderColor: colors.whiteTransparentMedium,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadedImage: {
    width: '100%',
    height: '100%',
    borderRadius: verticalScale(8),
  },
  deleteButton: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: colors.red,
    borderRadius: verticalScale(12),
    width: horizontalScale(24),
    height: verticalScale(24),
    alignItems: 'center',
    justifyContent: 'center',
  },
  facilitiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: verticalScale(10),
  },
  facilityCheckboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: horizontalScale(15),
    marginBottom: verticalScale(10),
  },
  facilityCheckbox: {
    width: horizontalScale(20),
    height: verticalScale(20),
    borderRadius: verticalScale(4),
    borderWidth: 1,
    borderColor: colors.whiteTransparentMedium,
    backgroundColor: colors.transparent,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: horizontalScale(8),
  },
  facilityCheckedBox: {
    backgroundColor: colors.violate,
    borderColor: colors.violate,
  },
  facilityCheckmark: {
    color: colors.white,
    fontSize: fontScale(12),
    fontFamily: fonts.semiBold,
  },
  facilityCheckboxText: {
    color: colors.white,
    fontSize: fontScale(14),
    fontFamily: fonts.regular,
  },
  loadingText: {
    color: colors.white,
    fontSize: fontScale(14),
    fontFamily: fonts.regular,
    textAlign: 'center',
    marginTop: verticalScale(10),
  },

  // Ticket Form Styles
  ticketFormContainer: {
    backgroundColor: colors.transparent,
    borderRadius: verticalScale(12),
    borderWidth: 1,
    borderColor: colors.whiteTransparentMedium,
    marginBottom: verticalScale(15),
    padding: horizontalScale(15),
  },
  ticketFormHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(15),
  },
  ticketFormTitle: {
    color: colors.white,
    fontSize: fontScale(16),
    fontFamily: fonts.semiBold,
  },
  removeTicketButton: {
    width: horizontalScale(30),
    height: verticalScale(30),
    borderRadius: verticalScale(15),
    backgroundColor: colors.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeTicketText: {
    color: colors.white,
    fontSize: fontScale(16),
    fontFamily: fonts.semiBold,
  },
  ticketFormContent: {
    // Container for ticket form fields
  },
  
  // Event Form Styles (matching Add Details screen)
  eventContainer: {
    backgroundColor: colors.vilate20,
    borderRadius: horizontalScale(12),
    padding: horizontalScale(16),
    marginBottom: verticalScale(16),
    borderWidth: 1,
    borderColor: colors.violate,
  },
  eventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(16),
  },
  eventTitle: {
    fontSize: fontScale(16),
    fontFamily: fonts.SemiBold,
    color: colors.white,
  },
  removeButton: {
    padding: horizontalScale(8),
  },
  removeButtonText: {
    fontSize: fontScale(16),
    color: colors.red,
    fontFamily: fonts.SemiBold,
  },
  inputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: verticalScale(12),
  },
  inputHalf: {
    width: '48%',
  },
  categorySection: {
    marginBottom: verticalScale(12),
  },
  categoryLabel: {
    fontSize: fontScale(14),
    fontFamily: fonts.Medium,
    color: colors.white,
    marginBottom: verticalScale(8),
  },
  categoryScrollView: {
    maxHeight: verticalScale(50),
  },
  categoryContainer: {
    paddingRight: horizontalScale(16),
  },
  categoryButton: {
    backgroundColor: colors.transparent,
    paddingVertical: verticalScale(8),
    paddingHorizontal: horizontalScale(16),
    borderRadius: horizontalScale(20),
    borderWidth: 1,
    borderColor: colors.white,
    marginRight: horizontalScale(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryButtonSelected: {
    backgroundColor: colors.violate,
    borderColor: colors.violate,
    shadowColor: colors.violate,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  categoryButtonText: {
    fontSize: fontScale(12),
    fontFamily: fonts.Medium,
    color: colors.textColor,
  },
  categoryButtonTextSelected: {
    color: colors.white,
    fontFamily: fonts.SemiBold,
  },
});