import { StyleSheet } from "react-native";
import { colors } from "../../../../../utilis/colors";
import { fonts } from "../../../../../utilis/fonts";
import {
  fontScale,
  horizontalScale,
  verticalScale,
} from "../../../../../utilis/appConstant";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gradient_dark_purple,
    paddingHorizontal: horizontalScale(16),
    paddingTop: verticalScale(40),
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: verticalScale(20),
  },
  headerTitle: {
    fontSize: fontScale(20),
    fontFamily: fonts.bold,
    color: colors.white,
    flex: 1,
    textAlign: "center",
  },
  headerSpacer: {
    width: horizontalScale(40),
  },
  profileContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: verticalScale(20),
    paddingHorizontal: horizontalScale(16),
  },
  profileImageContainer: {
    position: "relative",
    marginRight: horizontalScale(16),
  },
  profileImage: {
    width: horizontalScale(80),
    height: verticalScale(80),
    borderRadius: verticalScale(40),
    borderWidth: 2,
    borderColor: colors.violate,
  },
  editIconContainer: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: horizontalScale(24),
    height: verticalScale(24),
    borderRadius: verticalScale(12),
    backgroundColor: colors.violate,
    borderWidth: 2,
    borderColor: colors.gradient_dark_purple,
    alignItems: "center",
    justifyContent: "center",
  },
  profileDetails: {
    flex: 1,
  },
  profileName: {
    fontSize: fontScale(18),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(4),
  },
  profileEmail: {
    fontSize: fontScale(14),
    fontFamily: fonts.regular,
    color: colors.white,
    marginBottom: verticalScale(2),
  },
  profilePhone: {
    fontSize: fontScale(14),
    fontFamily: fonts.regular,
    color: colors.white,
  },
  smallContainer: {
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(12),
    padding: verticalScale(12),
    marginBottom: verticalScale(20),
    marginHorizontal: horizontalScale(16),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    alignItems: "center",
    justifyContent: "center",
    width: horizontalScale(200),
    height: verticalScale(130),
    marginTop: verticalScale(-80),
    alignSelf: "center",

  },
  smallContainerText: {
    fontSize: fontScale(14),
    fontFamily: fonts.medium,
    color: colors.white,
    marginBottom: verticalScale(4),
    marginTop: verticalScale(20),
  },
  hostNameContainerText: {
    fontSize: fontScale(14),
    fontFamily: fonts.medium,
    color: colors.violate,
    marginBottom: verticalScale(8),
    marginTop: verticalScale(2),
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: verticalScale(4),
    marginTop: verticalScale(4),
  },
  locationText: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    color: colors.white,
    marginLeft: horizontalScale(8),
    marginRight: horizontalScale(20),
    
  },
  descriptionText: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    color: colors.white,
    lineHeight: fontScale(16),
    marginTop: verticalScale(4),
  },
  actionButtonsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: verticalScale(20),
    paddingHorizontal: horizontalScale(16),
  },
  actionButton: {
    width: horizontalScale(50),
    height: verticalScale(50),
    borderRadius: verticalScale(25),
    backgroundColor: colors.cardBackground,
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: horizontalScale(10),
  },

  tabsContainer: {
    flexDirection: "row",
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(16),
    padding: verticalScale(2),
    marginBottom: verticalScale(20),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    shadowColor: colors.purpleBorder,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  tabButton: {
    flex: 1,
    paddingVertical: verticalScale(14),
    paddingHorizontal: horizontalScale(12),
    borderRadius: verticalScale(12),
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: horizontalScale(2),
  },
  activeTabButton: {
    backgroundColor: colors.violate,
    shadowColor: colors.violate,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  tabButtonText: {
    fontSize: fontScale(13),
    fontFamily: fonts.medium,
    color: colors.white,
    textAlign: "center",
  },
  activeTabButtonText: {
    fontFamily: fonts.bold,
    color: colors.white,
  },
  contentContainer: {
    flex: 1,
  },
  tabContent: {
    paddingBottom: verticalScale(100),
  },
  sectionTitle: {
    fontSize: fontScale(18),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(16),
  },
  boothCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(12),
    padding: verticalScale(16),
    marginBottom: verticalScale(12),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
  },
  boothInfo: {
    flex: 1,
  },
  boothName: {
    fontSize: fontScale(16),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(4),
  },
  boothDescription: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    color: colors.white,
    marginBottom: verticalScale(8),
  },
  boothDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  boothCapacity: {
    fontSize: fontScale(12),
    fontFamily: fonts.medium,
    color: colors.violate,
  },
  boothPrice: {
    fontSize: fontScale(14),
    fontFamily: fonts.bold,
    color: colors.white,
    marginRight: horizontalScale(8),
  },
  eventCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(12),
    padding: verticalScale(16),
    marginBottom: verticalScale(12),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
  },
  eventInfo: {
    flex: 1,
  },
  eventName: {
    fontSize: fontScale(16),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(4),
  },
  eventDate: {
    fontSize: fontScale(12),
    fontFamily: fonts.medium,
    color: colors.violate,
    marginBottom: verticalScale(4),
  },
  eventDescription: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    color: colors.white,
  },
  eventDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  eventPriceContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  eventPrice: {
    fontSize: fontScale(14),
    fontFamily: fonts.bold,
    color: colors.white,
    marginRight: horizontalScale(8),
  },
  pubCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(12),
    padding: verticalScale(16),
    marginBottom: verticalScale(12),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
  },
  pubInfo: {
    flex: 1,
  },
  pubName: {
    fontSize: fontScale(16),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(4),
  },
  pubDescription: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    color: colors.white,
    marginBottom: verticalScale(8),
  },
  pubDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  pubAvailability: {
    fontSize: fontScale(12),
    fontFamily: fonts.medium,
    color: colors.violate,
  },
  pubPrice: {
    fontSize: fontScale(14),
    fontFamily: fonts.bold,
    color: colors.white,
    marginRight: horizontalScale(8),
  },
  noDataText: {
    fontSize: fontScale(16),
    fontFamily: fonts.medium,
    color: colors.gray,
    textAlign: "center",
    marginTop: 20,
  },
  boothHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(6),
  },
  eventHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(6),
  },
  pubHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(6),
  },
  categoryTag: {
    backgroundColor: colors.violate,
    color: colors.white,
    fontSize: fontScale(10),
    fontFamily: fonts.medium,
    paddingHorizontal: horizontalScale(8),
    paddingVertical: verticalScale(4),
    borderRadius: verticalScale(12),
  },
  boothPriceContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pubPriceContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  eventCapacity: {
    fontSize: fontScale(12),
    fontFamily: fonts.medium,
    color: colors.violate,
  },
  profileCardContainer: {
    backgroundColor: colors.profileCardBackground,
    width: horizontalScale(350),
    height: verticalScale(180),
    opacity: 1,
    borderTopLeftRadius: horizontalScale(30),
    borderTopRightRadius: horizontalScale(30),
    borderBottomRightRadius: horizontalScale(40),
    borderBottomLeftRadius: horizontalScale(40),
    borderBottomWidth: 2,
    borderLeftWidth: 0.5,
    borderRightWidth: 0.5,
    alignSelf: "center",
   // borderTopWidth: 2,
    borderColor: colors.purpleBorder,
    borderBottomColor: colors.purpleBorder,
    padding: verticalScale(20),
    marginBottom: verticalScale(20),
    marginHorizontal: horizontalScale(16),
    shadowColor: colors.purpleBorder,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    marginTop: verticalScale(10),
  },
  profileContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  profileImageContainer: {
    position: "relative",
    marginRight: horizontalScale(16),
  },
  profileImage: {
    width: horizontalScale(80),
    height: verticalScale(80),
    borderRadius: verticalScale(40),
    borderWidth: 2,
    borderColor: colors.violate,
  },
  editIconContainer: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: horizontalScale(24),
    height: verticalScale(24),
    borderRadius: verticalScale(12),
    backgroundColor: colors.violate,
    borderWidth: 2,
    borderColor: colors.gradient_dark_purple,
    alignItems: "center",
    justifyContent: "center",
  },
  profileDetails: {
    flex: 1,
  },
  profileName: {
    fontSize: fontScale(18),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(4),
  },
  profileEmail: {
    fontSize: fontScale(14),
    fontFamily: fonts.regular,
    color: colors.white,
    marginBottom: verticalScale(2),
  },
  profilePhone: {
    fontSize: fontScale(14),
    fontFamily: fonts.regular,
    color: colors.white,
  },
});
