import { StyleSheet } from "react-native";
import { colors } from "../../../../../utilis/colors";
import { fonts } from "../../../../../utilis/fonts";
import {
  fontScale,
  horizontalScale,
  verticalScale,
} from "../../../../../utilis/appConstant";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gradient_dark_purple,
    paddingHorizontal: horizontalScale(16),
    paddingTop: verticalScale(40),
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: verticalScale(20),
  },
  headerTitle: {
    fontSize: fontScale(20),
    fontFamily: fonts.bold,
    color: colors.white,
    flex: 1,
    textAlign: "center",
  },
  headerSpacer: {
    width: horizontalScale(40),
  },
  clubInfoContainer: {
    flexDirection: "row",
    marginBottom: verticalScale(20),
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(16),
    padding: verticalScale(16),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
  },
  clubImage: {
    width: horizontalScale(100),
    height: verticalScale(100),
    borderRadius: verticalScale(12),
    marginRight: horizontalScale(16),
  },
  clubDetails: {
    flex: 1,
    justifyContent: "center",
  },
  clubName: {
    fontSize: fontScale(18),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(6),
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: verticalScale(4),
  },
  locationText: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    color: colors.white,
    marginLeft: horizontalScale(6),
  },
  ratingText: {
    fontSize: fontScale(12),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(8),
  },
  descriptionText: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    color: colors.white,
    lineHeight: fontScale(16),
  },

  tabsContainer: {
    flexDirection: "row",
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(16),
    padding: verticalScale(4),
    marginBottom: verticalScale(20),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
    shadowColor: colors.purpleBorder,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  tabButton: {
    flex: 1,
    paddingVertical: verticalScale(14),
    paddingHorizontal: horizontalScale(12),
    borderRadius: verticalScale(12),
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: horizontalScale(2),
  },
  activeTabButton: {
    backgroundColor: colors.violate,
    shadowColor: colors.violate,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  tabButtonText: {
    fontSize: fontScale(13),
    fontFamily: fonts.medium,
    color: colors.white,
    textAlign: "center",
  },
  activeTabButtonText: {
    fontFamily: fonts.bold,
    color: colors.white,
  },
  contentContainer: {
    flex: 1,
  },
  tabContent: {
    paddingBottom: verticalScale(100),
  },
  sectionTitle: {
    fontSize: fontScale(18),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(16),
  },
  boothCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(12),
    padding: verticalScale(16),
    marginBottom: verticalScale(12),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
  },
  boothInfo: {
    flex: 1,
  },
  boothName: {
    fontSize: fontScale(16),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(4),
  },
  boothDescription: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    color: colors.white,
    marginBottom: verticalScale(8),
  },
  boothDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  boothCapacity: {
    fontSize: fontScale(12),
    fontFamily: fonts.medium,
    color: colors.violate,
  },
  boothPrice: {
    fontSize: fontScale(14),
    fontFamily: fonts.bold,
    color: colors.white,
    marginRight: horizontalScale(8),
  },
  eventCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(12),
    padding: verticalScale(16),
    marginBottom: verticalScale(12),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
  },
  eventInfo: {
    flex: 1,
  },
  eventName: {
    fontSize: fontScale(16),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(4),
  },
  eventDate: {
    fontSize: fontScale(12),
    fontFamily: fonts.medium,
    color: colors.violate,
    marginBottom: verticalScale(4),
  },
  eventDescription: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    color: colors.white,
  },
  eventDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  eventPriceContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  eventPrice: {
    fontSize: fontScale(14),
    fontFamily: fonts.bold,
    color: colors.white,
    marginRight: horizontalScale(8),
  },
  pubCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.cardBackground,
    borderRadius: verticalScale(12),
    padding: verticalScale(16),
    marginBottom: verticalScale(12),
    borderWidth: 1,
    borderColor: colors.purpleBorder,
  },
  pubInfo: {
    flex: 1,
  },
  pubName: {
    fontSize: fontScale(16),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: verticalScale(4),
  },
  pubDescription: {
    fontSize: fontScale(12),
    fontFamily: fonts.regular,
    color: colors.white,
    marginBottom: verticalScale(8),
  },
  pubDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  pubAvailability: {
    fontSize: fontScale(12),
    fontFamily: fonts.medium,
    color: colors.violate,
  },
  pubPrice: {
    fontSize: fontScale(14),
    fontFamily: fonts.bold,
    color: colors.white,
    marginRight: horizontalScale(8),
  },
  noDataText: {
    fontSize: fontScale(16),
    fontFamily: fonts.medium,
    color: colors.gray,
    textAlign: "center",
    marginTop: 20,
  },
  boothHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(6),
  },
  eventHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(6),
  },
  pubHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(6),
  },
  categoryTag: {
    backgroundColor: colors.violate,
    color: colors.white,
    fontSize: fontScale(10),
    fontFamily: fonts.medium,
    paddingHorizontal: horizontalScale(8),
    paddingVertical: verticalScale(4),
    borderRadius: verticalScale(12),
  },
  boothPriceContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pubPriceContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  eventCapacity: {
    fontSize: fontScale(12),
    fontFamily: fonts.medium,
    color: colors.violate,
  },
});
