import { StyleSheet } from "react-native";
import { colors } from "../../utilis/colors";
import { fonts } from "../../utilis/fonts";
import appConstant, {
  fontScale,
  horizontalScale,
  verticalScale,
} from "../../utilis/appConstant";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    paddingTop: verticalScale(50),
    paddingHorizontal: horizontalScale(20),
    alignItems: 'flex-end',
  },
  statusBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(10),
  },
  statusIcons: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
  },
  skipText: {
    
    color: colors.white,
    fontWeight: "600",
    fontSize: fontScale(16),
    lineHeight: fontScale(24),
    fontFamily: fonts.semiBold,
  },
  titleSection: {
    paddingHorizontal: horizontalScale(20),
    marginBottom: verticalScale(30),
    alignItems: "center",
  },
  welcomeText: {
    fontSize: fontScale(27),
    fontFamily: fonts.BlackerBold,
    alignSelf: 'center',
    textAlign: 'center',
    marginTop:  fontScale(30),
    fontWeight: 500,
    lineHeight: fontScale(24),
    width: fontScale(335),
    height: fontScale(38),
    color: colors.violate,
  },
  appName: {
    fontSize: fontScale(36),
    fontFamily: fonts.BlackerBold,
    fontWeight: "700",
    color: colors.violate,
    lineHeight: fontScale(36) * 1.1,
    letterSpacing: 0,
    marginBottom: verticalScale(15),
    textAlign: "center",
  },
  tagline: {
    fontSize: fontScale(14),
    fontFamily: fonts.BlackerRegular,
    fontWeight: "400",
    color: colors.white,
    lineHeight: fontScale(15.95),
    letterSpacing: 1,
    marginBottom: verticalScale(20),
    textAlign: "center",
  },
  description: {
    fontSize: fontScale(14),
    fontFamily: fonts.Regular,
    fontWeight: "400",
    color: colors.white,
    lineHeight: 20,
    letterSpacing: 0,
    opacity: 0.8,
    textAlign: "center",
    paddingHorizontal: horizontalScale(20),
  },
  logoSection: {
    alignItems: "center",
  },
  logoContainer: {
    width: horizontalScale(120),
    height: verticalScale(120),
    borderRadius: 60,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: verticalScale(15),
    shadowColor: colors.violate,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  logoText: {
    fontSize: fontScale(48),
    fontFamily: fonts.BlackerBold,
    fontWeight: "700",
    color: colors.white,
    textAlign: "center",
  },
  logoSubtext: {
    fontSize: fontScale(26),
    fontFamily: fonts.BlackerMedium,
    alignSelf: 'center',
    textAlign: 'center',
    marginTop:  fontScale(30),
    fontWeight: 500,
    lineHeight: fontScale(24),
    width: fontScale(335),
    height: fontScale(38),
    color: colors.violate,
  },
  socialSection: {
    paddingHorizontal: horizontalScale(20),
    marginBottom: verticalScale(15),
  },
  socialButton: {
    backgroundColor: colors.white,
    width: horizontalScale(333),
    height: verticalScale(49),
    borderRadius: verticalScale(30),
    marginBottom: verticalScale(15),
    paddingTop: verticalScale(12),
    paddingRight: horizontalScale(66),
    paddingBottom: verticalScale(12),
    paddingLeft: horizontalScale(66),
    borderWidth: 1,
    borderColor: colors.lightGray,
    alignSelf: "center",
  },
  socialButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  appleIcons: {
    fontSize: fontScale(20),
    marginRight: horizontalScale(10),
  },
  socialButtonText: {
    fontSize: fontScale(16),
    lineHeight: fontScale(24),
    fontWeight: "600",
    fontFamily: fonts.semiBold,
    color: colors.darkGray,
  },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: verticalScale(5),
    marginBottom: verticalScale(15),
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.disableGray,
    opacity: 0.3,
  },
  dividerText: {
    fontWeight: "500",
    color: colors.white,
    fontSize: fontScale(18),
    fontFamily: fonts.medium,
    marginHorizontal: horizontalScale(15),
  },
  roleSection: {
    paddingHorizontal: horizontalScale(20),
    marginBottom: verticalScale(30),
  },
  sectionTitle: {
    fontSize: fontScale(14),
    fontWeight: "400",
    fontFamily: fonts.Regular,
    color: colors.white,
    marginBottom: verticalScale(15),
    textAlign: "center",
  },
  roleOptions: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: horizontalScale(40),
  },
  roleOption: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    padding: verticalScale(10),
  },
  selectedRole: {
    // No additional styling needed for selected role
  },
  roleContent: {
    alignItems: "center",
  },
  roleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: horizontalScale(12),
  },
  roleIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: colors.violate,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  selectedIconContainer: {
    borderColor: colors.violate,
    backgroundColor: colors.violate,
  },
  radioButton: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.disableGray,
    alignItems: "center",
    justifyContent: "center",
  },
  selectedRadio: {
    borderColor: colors.violate,
  },
  radioInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.violate,
  },
  roleIcon: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  roleText: {
    fontFamily: fonts.Regular,
    fontWeight: "400",
    fontStyle: "normal",
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0,
    color: colors.white,
    textAlign: "center",
  },
  ctaSection: {
    paddingHorizontal: horizontalScale(20),
    marginBottom: verticalScale(30),
    alignItems: "center",
  },
  ctaText: {
    fontSize: fontScale(18),
    fontFamily: fonts.semiBold,
    fontWeight: "600",
    color: colors.violate,
    textAlign: "center",
  },
  buttonSection: {
    paddingHorizontal: horizontalScale(20),
    paddingBottom: verticalScale(30),
    flexDirection: "row",
    gap: horizontalScale(10),
  },
  signUpButton: {
    width: horizontalScale(169),
    height: verticalScale(50),
    borderRadius: verticalScale(30),
    borderWidth: 1,
    marginBottom: verticalScale(0),
  },
  signInButton: {
    width: horizontalScale(169),
    height: verticalScale(50),
    borderRadius: verticalScale(30),
    borderWidth: 1,
    borderColor: colors.violate,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  signInButtonText: {
    fontSize: fontScale(16),
    lineHeight: fontScale(24),
    fontWeight: "600",
    fontFamily: fonts.semiBold,
    color: colors.violate,
  },
});
